server:
  port: 9002
  tomcat.uri-encoding: UTF-8
#mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      username: wpmk
      password: Wpmk@123
      url: jdbc:mysql://39.104.95.252:3316/wpmk_micromall?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
      initial-size: 1
      min-idle: 3
      max-active: 20
      max-wait: 60000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
      min-evictable-idle-time-millis: 30000
      time-between-eviction-runs-millis: 60000
      validation-query-timeout: 2
      filters: stat,wall,log4j2
      aop-patterns: com.wpmk.micromall.backstage*
      filter:
        #监控统计
        stat:
          enabled: true
          db-type: mysql
          #打印慢sql
          log-slow-sql: true
          # 超过300毫秒即为慢sql
          slow-sql-millis: 300
        wall:
          enabled: true
          db-type: mysql
          # 对认定的攻击sql进行日志输出
          log-violation: true
          # 对认定的攻击sql抛出异常
          throw-exception: true
          config:
            # 是否允许下述操作
            alter-table-allow: false
            truncate-allow: false
            drop-table-allow: false
            update-where-none-check: true
            # metadata会暴露数据的表结构
            metadata-allow: true
            multi-statement-allow: true
            none-base-statement-allow: true
      # 数据库连接池监控页面插件
      stat-view-servlet:
        enabled: true
        url-pattern: '/druid/*'
        reset-enable: true
        login-username: admin
        login-password: admin
        allow:
        deny:
# redis配置
  redis:
    port: 6379
    host: 39.104.95.252
    #host: 172.24.100.198
    timeout: 5000ms # 连接超时时间（毫秒）
    jedis:
      pool:
        max-wait: -1ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0
    password: Wpmk@123 # 连接池中的最小空闲连接


  #注册接口
#eureka:
#  client:
#    #由于该应用为注册中心,所以设置为false,代表不向注册中心注册自己
#    registerWithEureka: true
#    #由于注册中心的职责就是维护服务实例,它并不需要去检索服务,所以也设置为false
#    fetchRegistry: true
#    serviceUrl:
#       defaultZone: http://admin:123123@47.94.208.71:8001/eureka/,http://admin:123123@47.94.208.71:8002/eureka/,http://admin:123123@47.94.208.71:8003/eureka/









